### PR TITLE
Fix/rewrite sync

### LINKED ISSUE #268: [cob_scan_unifier] LookupError on start up
Appears once on startup, probably simply requires a sleep after tf::TransformListener initialization (for filling the buffer):

```
Node: /scan_unifier
Time: 16:05:39.612337463 (2016-03-04)
Severity: Error
Published Topics: /rosout, /scan_unified

Lookup would require extrapolation into the past.  Requested time 1457103936.557201524 but the earliest data is at time 1457103937.074180613, when looking up transform from frame [base_laser_front_link] to frame [base_link]

Location:
/u/fxm/git/care-o-bot/src/cob_driver/cob_scan_unifier/src/scan_unifier_node.cpp:LaserScan scan_unifier_node::unifieLaserScans:252
```

Also, `unifieLaserScans` should be `unifyLaserScans` :wink:

### PR DESCRIPTION
**Pull request by ghost**
Use message filters to sync the scans.

fix https://github.com/ipa320/cob_driver/issues/268

### CODE REVIEW

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 1]
```diff
@@ -58,30 +58,79 @@
...
+      synchronizer3_ = new message_filters::Synchronizer<SyncPolicy>(SyncPolicy(3), *message_filter_subscribers_.at(0), *message_filter_subscribers_.at(1), *message_filter_subscribers_.at(2));
+      synchronizer3_->setInterMessageLowerBound(0, ros::Duration(0.167));
+      synchronizer3_->setInterMessageLowerBound(1, ros::Duration(0.167));
+      synchronizer3_->setInterMessageLowerBound(2, ros::Duration(0.167));
+      synchronizer3_->registerCallback(boost::bind(&ScanUnifierNode::messageFilterCallback, this, _1, _2, _3));
+      break;
+    }
+    default:
+      ROS_ERROR_STREAM(config_.number_input_scans << " topics have been set as input, but scan_unifier doesn't support this.");
+      return;
```
Comment (mgruhler) [inline cob_scan_unifier/src/scan_unifier_node.cpp:109]: Hmm, I don't like that this can only be done for 2 or 3 scans.
This was better in the old implementation. Is there a way to achieve the same here?

**Review by mgruhler — CHANGES_REQUESTED** [review]

File: cob_scan_unifier/src/scan_unifier_node.cpp (hunk 1 above)
Comment (ghost) [reply cob_scan_unifier/src/scan_unifier_node.cpp:109]: I don't like this too, but message_filters::TimeSynchronizer is implemented for a max of 9 scans, with a separate impl for every number-of-scanners. I tried but I didn't find a way to make it number-of-scanners-independent. I talked to ipa-fxm about this and he didn't know a better solution either.

Comment (mgruhler) [reply cob_scan_unifier/src/scan_unifier_node.cpp:109]: To me, the documentation on the [wiki](http://wiki.ros.org/message_filters#Policy-Based_Synchronizer_.5BROS_1.1.2B-.5D) seems to state that we can sync up to 9 topics:

> C++: Up to 9 separate filters, each of which is of the form void callback(const boost::shared_ptr<M const>&). The number of filters supported is determined by the number of template arguments the class was created with.

I'd say, this should be fine then...

Comment (mgruhler) [reply cob_scan_unifier/src/scan_unifier_node.cpp:109]: @ipa-fxm fyi
@mig-em please note if this is superseeding another PR and cross-referene.

Comment (mgruhler) [reply cob_scan_unifier/src/scan_unifier_node.cpp:109]: Well, shouldn't we make it in a way then to be able to handle the nine scanners then? Use a vector of synchronizers, maybe?

Comment (mgruhler) [reply cob_scan_unifier/src/scan_unifier_node.cpp:109]: alright, ignore this one: discussed in person.

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 2]
```diff
@@ -123,150 +166,99 @@ void scan_unifier_node::getParams()
...
-            vec_laser_struct_.at(i).current_scan_msg.header.stamp, ros::Duration(3.0));
+        if (!listener_.waitForTransform(frame_, current_scans.at(i)->header.frame_id,
+                                        current_scans.at(i)->header.stamp, ros::Duration(3.0)))
+        {
+          continue;
+        }
+        else
+        {
+          ROS_WARN_STREAM("Scan unifier skipped scan with " << current_scans.at(i)->header.stamp << " stamp.");
+        }
```
Comment (mgruhler) [inline cob_scan_unifier/src/scan_unifier_node.cpp]: Is this correct? We `continue` when `waitForTransform` times out and throw a warning if not. Or did I mix that up?

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 3]
```diff
@@ -58,30 +58,79 @@
...
 
-  pthread_mutex_init(&m_mutex, NULL);
+  switch (config_.number_input_scans)
+  {
+    case 2:
+    {
+      typedef message_filters::sync_policies::ApproximateTime<sensor_msgs::LaserScan, sensor_msgs::LaserScan> SyncPolicy;
+      synchronizer2_ = new message_filters::Synchronizer<SyncPolicy>(SyncPolicy(2), *message_filter_subscribers_.at(0), *message_filter_subscribers_.at(1));
+      synchronizer2_->setInterMessageLowerBound(0, ros::Duration(0.167));
+      synchronizer2_->setInterMessageLowerBound(1, ros::Duration(0.167));
```
Comment (mgruhler) [inline cob_scan_unifier/src/scan_unifier_node.cpp]: How did you choose this number?

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 4]
```diff
@@ -58,30 +58,79 @@
...
+      synchronizer3_->registerCallback(boost::bind(&ScanUnifierNode::messageFilterCallback, this, _1, _2, _3));
+      break;
+    }
+    default:
+      ROS_ERROR_STREAM(config_.number_input_scans << " topics have been set as input, but scan_unifier doesn't support this.");
+      return;
+  }
 
-  initLaserScanStructs();
+//  synchronizer_->registerCallback(&ScanUnifierNode::messageFilterCallback);
```
Comment (mgruhler) [inline cob_scan_unifier/src/scan_unifier_node.cpp]: remove, this is not used.

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 5]
```diff
@@ -123,150 +166,99 @@ void scan_unifier_node::getParams()
...
       }
     }
     ROS_DEBUG("Creating message header");
-    unified_scan.header = vec_laser_struct_.at(0).current_scan_msg.header;
-    unified_scan.header.frame_id = "base_link";
+    unified_scan.header = current_scans.at(0)->header;
+    unified_scan.header.frame_id = frame_;
     unified_scan.angle_increment = M_PI/180.0/2.0;
     unified_scan.angle_min = -M_PI + unified_scan.angle_increment*0.01;
     unified_scan.angle_max =  M_PI - unified_scan.angle_increment*0.01;
```
Comment (mgruhler) [inline cob_scan_unifier/src/scan_unifier_node.cpp:227]: This might actually be the reason for #249 

Also, the above restricts this unifier to be used with a spacing fo 0.5°. This should probably be adapted as well.
Something like "biggest common denominator" but in float ;-)
Added it to #249

**Review by mgruhler — CHANGES_REQUESTED** [review]

File: cob_scan_unifier/src/scan_unifier_node.cpp (hunk 3 above)
Comment (fmessmer) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: =0.5*(1/12) // half of expected scanner rate at 12Hz (I guess)

File: cob_scan_unifier/src/scan_unifier_node.cpp (hunk 1 above)
Comment (fmessmer) [reply cob_scan_unifier/src/scan_unifier_node.cpp:109]: For the sake of completeness: [Synchronizer-API](http://docs.ros.org/indigo/api/message_filters/html/c++/classmessage__filters_1_1TimeSynchronizer.html) is implemented in the same (ugly) way...

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 6]
```diff
@@ -58,30 +58,79 @@
...
+    {
+      delete(synchronizer2_);
+      break;
+    }
+    case 3:
+    {
+      delete(synchronizer3_);
+      break;
+    }
+  }
```
Comment (fmessmer) [inline cob_scan_unifier/src/scan_unifier_node.cpp]: I guess there is actually no need to switch...you could just `delete` both...

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 7]
```diff
@@ -90,17 +139,11 @@ scan_unifier_node::~scan_unifier_node(){}
...
-
-  if(!pnh_.hasParam("loop_rate"))
-  {
-    ROS_WARN("No parameter loop_rate on parameter server. Using default value [100.0].");
-  }
-  pnh_.param("loop_rate", config_.loop_rate, (double)100.0);
-
   XmlRpc::XmlRpcValue topicList;
 
+  // TODO short parsing
```
Comment (fmessmer) [inline cob_scan_unifier/src/scan_unifier_node.cpp]: Link to list retrieval: http://wiki.ros.org/roscpp/Overview/Parameter%20Server#Retrieving_Lists

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 8]
```diff
@@ -123,150 +166,99 @@ void scan_unifier_node::getParams()
...
-{
-  return config_.loop_rate;
+  if(!pnh_.hasParam("frame"))
+  {
+    ROS_WARN("No parameter frame on parameter server. Using default value [base_link].");
+    frame_ = "base_link";
+  }
+  else
+  {
+    pnh_.getParam("frame", frame_);
```
Comment (fmessmer) [inline cob_scan_unifier/src/scan_unifier_node.cpp]: just use "default version" (`nh.param<std::string>("default_param", default_param, "default_value");`) ?

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 9]
```diff
@@ -123,150 +166,99 @@ void scan_unifier_node::getParams()
...
-/**
- * @function initLaserScanStructs
- * @brief initialize a vector of laser scan structs (member variable vec_laser_struct_) with a given number
- * (from parameter server, stored in config_ struct)
- *
- * input: -
- * output: -
- */
-void scan_unifier_node::initLaserScanStructs()
+void ScanUnifierNode::messageFilterCallback(const sensor_msgs::LaserScan::ConstPtr& first_scanner, const sensor_msgs::LaserScan::ConstPtr& second_scanner)
```
Comment (fmessmer) [inline cob_scan_unifier/src/scan_unifier_node.cpp]: I'd prefer `scan1` instead of `first_scanner`, `scan2` instead of `second_scanner`....

File: cob_scan_unifier/src/scan_unifier_node.cpp (hunk 2 above)
Comment (fmessmer) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: I am confused as well....
With the Synchronizer we never should need to skip a scan any more...that's the whole point....

File: cob_scan_unifier/src/scan_unifier_node.cpp (hunk 3 above)
Comment (mgruhler) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: Hmm, is it safe to assume this is the lower bound? Or would we want to merge scans with a frequency <12Hz as well?

Comment (fmessmer) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: Is 12Hz a configurable parameter for the scanners?
Then we at least should make the computation of the bounds based on a parameter as we might unify scans from other sensors with different publish rate as well...

Comment (mgruhler) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: To be honest, I'm not sure. There is a [parameter about the publish rate in the S300 driver](https://github.com/ipa320/cob_driver/blob/indigo_dev/cob_sick_s300/ros/src/cob_sick_s300.cpp#L145-L146). But: afaik, this is [not respected](https://github.com/ipa320/cob_driver/blob/indigo_dev/cob_sick_s300/ros/src/cob_sick_s300.cpp#L259-L261). The new S300 Expert do have an output of about 25Hz (phyiscal max of the scanner) with our driver.

The frequency of the data output depends on the configuration in the scanner itself.

Also, other scanners have other frequencies... And we could actually try to merge scanners with different frequencies. But this gets ugly.

Comment (fmessmer) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: let's make it work for our use-case....either 2 s300 (raw) or 3 s300 (cob4)...then test it...eventually it's **cob**_scan_unifier anyway
(but add a comment about where the formula comes from, i.e. relate it to expected s300 publish rate)

Comment (mgruhler) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: fine for me. Then we can stick to 12Hz (even though the scanner itself could be configured to send out with less frequency without respecting anything in the driver. we just should not do that).

Then we can stick with the 0.5° spacing in my comment below as well...

Comment (fmessmer) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: Well, I meant **after** successful testing we could at least introduce parameters to make the scan_unifier node configurable...but those parameters would be scan_unifier parameters and not related to parameters (of the same meaning) of the scanner driver, though

Comment (mgruhler) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: Yes, I fully understand this. I just wanted to point out that this is in the end not independent (high expected frequency in the unifier + low frequency in the scanner = no unified scan).

But I'm sure I'm preaching to the choir here :-)

File: cob_scan_unifier/src/scan_unifier_node.cpp (hunk 2 above)
Comment (ghost) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: Synchronizer does only sync the messages, so it doesn't make any difference for the tf problem...

File: cob_scan_unifier/src/scan_unifier_node.cpp [hunk 10]
```diff
@@ -90,183 +126,130 @@ scan_unifier_node::~scan_unifier_node(){}
...
+//      {
+//        ROS_ASSERT(topicList[i].getType() == XmlRpc::XmlRpcValue::TypeString);
+//        config_.input_scan_topics.push_back(static_cast<std::string>(topicList[i]));
+//
+//        ROS_DEBUG_STREAM("Parsed the scan topic: " << config_.input_scan_topics.back());
+//      }
+//
+//      config_.number_input_scans = config_.input_scan_topics.size();
+//    }
+//  }
```
Comment (mgruhler) [inline cob_scan_unifier/src/scan_unifier_node.cpp]: This could/should be removed...

**Review by mgruhler — CHANGES_REQUESTED** [review]

File: cob_scan_unifier/src/scan_unifier_node.cpp (hunk 2 above)
Comment (mgruhler) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: Okay, this is fine.

But: Isn't this still the wrong way around?

Comment (fmessmer) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: Well, now that I'm looking at it:
**We** are handing over the `tf::TransformListener` object to the `projector_`. So in case all the `waitForTransform` magic we do in order to make the `transformLaserScanToPointCloud` work....maybe we just need to make our `listener_` object work!

Because currently it's using the default constructor (http://docs.ros.org/indigo/api/tf/html/c++/classtf_1_1TransformListener.html), i.e. default values for `max_cache_time`...maybe we can tweak something here...what also helps qutie often is "wait a little" at the end of the constructor to let the listener_ fill its cache...as we are seeing this problem only in the very beginning...

Also, is this `ROS_WARN_STREAM` still seen in the log? Because maybe the better time synchronization now does not give us messy timestamps as the "old" synchronization might have...

Last not least, in case the `!waitForTranform` case cannot be avoided by any means...should we return, i.e. skip all scans of current cycle or only skip the scan that failed, i.e. incomplete scan unified

Comment (fmessmer) [reply cob_scan_unifier/src/scan_unifier_node.cpp]: > Is this correct? We `continue` when `waitForTransform` times out and throw a warning if not. Or did I mix that up?

ja is wrong!

**Review by mgruhler — APPROVED** [review]
